const SOLARIZED_COLORS = [
  {paletteName: 'Base03', colors: '#002b36'},
  {paletteName: 'Base02', colors: '#073642'},
  {paletteName: 'Base01', colors: '#586e75'},
  {paletteName: 'Base00', colors: '#657b83'},
  {paletteName: 'Base0', colors: '#839496'},
  {paletteName: 'Base1', colors: '#93a1a1'},
  {paletteName: 'Base2', colors: '#eee8d5'},
  {paletteName: 'Base3', colors: '#fdf6e3'},
  {paletteName: 'Yellow', colors: '#b58900'},
  {paletteName: 'Orange', colors: '#cb4b16'},
  {paletteName: 'Red', colors: '#dc322f'},
  {paletteName: 'Magenta', colors: '#d33682'},
  {paletteName: 'Violet', colors: '#6c71c4'},
  {paletteName: 'Blue', colors: '#268bd2'},
  {paletteName: 'Cyan', colors: '#2aa198'},
  {paletteName: 'Green', colors: '#859900'},
]

const CRYSTAL_SEA = [
  {paletteName: 'Soft Coral', colors: '#85d2b9'},
  {paletteName: 'Green Aqua', colors: '#5d9c94'},
  {paletteName: 'Nature Green', colors: '#3b898b'},
  {paletteName: 'Elegant Blue', colors: '#447a94'},
  {paletteName: 'Softened Royal', colors: '#3c6081'},
]

const ORANGE_CREME = [
  {paletteName: 'Vanilla', colors: '#fdf2b8'},
  {paletteName: 'Orange', colors: '#e88200'},
  {paletteName: 'Burnt Orange', colors: '#cb2800'},
  {paletteName: 'Coffee', colors: '#34262b'},
]

const GOLDEN_LAVENDER = [
  {paletteName: 'Royal Gold', colors: '#a97218'},
  {paletteName: 'Bright Currency', colors: '#e0b34a'},
  {paletteName: 'Serious Tempo', colors: '#77526b'},
  {paletteName: 'Spring Memories', colors: '#a26499'},
  {paletteName: 'Bright Fate', colors: '#e6a4ff'},
]

const MUTED_SPLASH = [
  {paletteName: 'Saturated Yellow', colors: '#d5d609'},
  {paletteName: 'Prominent Pink', colors: '#dd2164'},
  {paletteName: 'Nature Heritage', colors: '#079041'},
  {paletteName: 'Dark Green Aqua', colors: '#1c817e'},
  {paletteName: 'Colorful Splash', colors: '#6e04a9'},
]

const WILD_JUNGLE = [
  {paletteName: 'Royal Pink', colors: '#eabaac'},
  {paletteName: 'Wild Orange', colors: '#be3400'},
  {paletteName: 'Dark Blue', colors: '#020d22'},
  {paletteName: 'Jungle Green', colors: '#015045'},
]

const SUMMER_TONES = [
  {paletteName: 'Creme', colors: '#fff8d8'},
  {paletteName: 'Crystal Blue', colors: '#6db9d5'},
  {paletteName: 'Royal Blue', colors: '#072e74'},
  {paletteName: 'Yellow Mustard', colors: '#a4c200'},
]

const CRAFTSMAN_COLLECTION = [
  {paletteName: 'Soft Cream', colors: '#d7c797'},
  {paletteName: 'Royal Wood', colors: '#845422'},
  {paletteName: 'Bright Accent', colors: '#ead61c'},
  {paletteName: 'Classic Wood', colors: '#a47c48'},
  {paletteName: 'Dark Accent', colors: '#000000'},
]

const STRAWBERRY_RAIN = [
  {paletteName: 'Soft Red', colors: '#ff7474'},
  {paletteName: 'Cotton Candy', colors: '#f695a4'},
  {paletteName: 'Happy Green', colors: '#cff4df'},
  {paletteName: 'Coral King', colors: '#abdfd6'},
  {paletteName: 'Calm Waves', colors: '#a4cddd'},
]

const DISCORD_COLORS = [
  {paletteName: 'Digital Purple', colors: '#7289da'},
  {paletteName: 'Serious Etiquette', colors: '#424549'},
  {paletteName: 'Elegant Night', colors: '#36393e'},
  {paletteName: 'Classic Curtain', colors: '#282b30'},
  {paletteName: 'Real Night', colors: '#1e2124'},
]

const COLOR_PALETTES = [
  {paletteName: 'Solarized', colors: SOLARIZED_COLORS},
  {paletteName: 'Crystal Sea', colors: CRYSTAL_SEA},
  {paletteName: 'Muted Splash', colors: MUTED_SPLASH},
  {paletteName: 'Orange Creme', colors: ORANGE_CREME},
  {paletteName: 'Golden Lavender', colors: GOLDEN_LAVENDER},
  {paletteName: 'Craftsman Collection', colors: CRAFTSMAN_COLLECTION},
  {paletteName: 'Wild Jungle', colors: WILD_JUNGLE},
  {paletteName: 'Strawberry In The Rain', colors: STRAWBERRY_RAIN},
  {paletteName: 'Summer Tones', colors: SUMMER_TONES},
  {paletteName: 'Discord', colors: DISCORD_COLORS},
]

const COLORS = [
  {paletteName: 'AliceBlue', colors: '#F0F8FF'},
  {paletteName: 'AntiqueWhite', colors: '#FAEBD7'},
  {paletteName: 'Aqua', colors: '#00FFFF'},
  {paletteName: 'Aquamarine', colors: '#7FFFD4'},
  {paletteName: 'Azure', colors: '#F0FFFF'},
  {paletteName: 'Beige', colors: '#F5F5DC'},
  {paletteName: 'Bisque', colors: '#FFE4C4'},
  {paletteName: 'Black', colors: '#000000'},
  {paletteName: 'BlanchedAlmond', colors: '#FFEBCD'},
  {paletteName: 'Blue', colors: '#0000FF'},
  {paletteName: 'BlueViolet', colors: '#8A2BE2'},
  {paletteName: 'Brown', colors: '#A52A2A'},
  {paletteName: 'BurlyWood', colors: '#DEB887'},
  {paletteName: 'CadetBlue', colors: '#5F9EA0'},
  {paletteName: 'Chartreuse', colors: '#7FFF00'},
  {paletteName: 'Chocolate', colors: '#D2691E'},
  {paletteName: 'Coral', colors: '#FF7F50'},
  {paletteName: 'CornflowerBlue', colors: '#6495ED'},
  {paletteName: 'Cornsilk', colors: '#FFF8DC'},
  {paletteName: 'Crimson', colors: '#DC143C'},
  {paletteName: 'Cyan', colors: '#00FFFF'},
  {paletteName: 'DarkBlue', colors: '#00008B'},
  {paletteName: 'DarkCyan', colors: '#008B8B'},
  {paletteName: 'DarkGoldenRod', colors: '#B8860B'},
  {paletteName: 'DarkGray', colors: '#A9A9A9'},
  {paletteName: 'DarkGrey', colors: '#A9A9A9'},
  {paletteName: 'DarkGreen', colors: '#006400'},
  {paletteName: 'DarkKhaki', colors: '#BDB76B'},
  {paletteName: 'DarkMagenta', colors: '#8B008B'},
  {paletteName: 'DarkOliveGreen', colors: '#556B2F'},
  {paletteName: 'Darkorange', colors: '#FF8C00'},
  {paletteName: 'DarkOrchid', colors: '#9932CC'},
  {paletteName: 'DarkRed', colors: '#8B0000'},
  {paletteName: 'DarkSalmon', colors: '#E9967A'},
  {paletteName: 'DarkSeaGreen', colors: '#8FBC8F'},
  {paletteName: 'DarkSlateBlue', colors: '#483D8B'},
  {paletteName: 'DarkSlateGray', colors: '#2F4F4F'},
  {paletteName: 'DarkSlateGrey', colors: '#2F4F4F'},
  {paletteName: 'DarkTurquoise', colors: '#00CED1'},
  {paletteName: 'DarkViolet', colors: '#9400D3'},
  {paletteName: 'DeepPink', colors: '#FF1493'},
  {paletteName: 'DeepSkyBlue', colors: '#00BFFF'},
  {paletteName: 'DimGray', colors: '#696969'},
  {paletteName: 'DimGrey', colors: '#696969'},
  {paletteName: 'DodgerBlue', colors: '#1E90FF'},
  {paletteName: 'FireBrick', colors: '#B22222'},
  {paletteName: 'FloralWhite', colors: '#FFFAF0'},
  {paletteName: 'ForestGreen', colors: '#228B22'},
  {paletteName: 'Fuchsia', colors: '#FF00FF'},
  {paletteName: 'Gainsboro', colors: '#DCDCDC'},
  {paletteName: 'GhostWhite', colors: '#F8F8FF'},
  {paletteName: 'Gold', colors: '#FFD700'},
  {paletteName: 'GoldenRod', colors: '#DAA520'},
  {paletteName: 'Gray', colors: '#808080'},
  {paletteName: 'Grey', colors: '#808080'},
  {paletteName: 'Green', colors: '#008000'},
  {paletteName: 'GreenYellow', colors: '#ADFF2F'},
  {paletteName: 'HoneyDew', colors: '#F0FFF0'},
  {paletteName: 'HotPink', colors: '#FF69B4'},
  {paletteName: 'IndianRed', colors: '#CD5C5C'},
  {paletteName: 'Indigo', colors: '#4B0082'},
  {paletteName: 'Ivory', colors: '#FFFFF0'},
  {paletteName: 'Khaki', colors: '#F0E68C'},
  {paletteName: 'Lavender', colors: '#E6E6FA'},
  {paletteName: 'LavenderBlush', colors: '#FFF0F5'},
  {paletteName: 'LawnGreen', colors: '#7CFC00'},
  {paletteName: 'LemonChiffon', colors: '#FFFACD'},
  {paletteName: 'LightBlue', colors: '#ADD8E6'},
  {paletteName: 'LightCoral', colors: '#F08080'},
  {paletteName: 'LightCyan', colors: '#E0FFFF'},
  {paletteName: 'LightGoldenRodYellow', colors: '#FAFAD2'},
  {paletteName: 'LightGray', colors: '#D3D3D3'},
  {paletteName: 'LightGrey', colors: '#D3D3D3'},
  {paletteName: 'LightGreen', colors: '#90EE90'},
  {paletteName: 'LightPink', colors: '#FFB6C1'},
  {paletteName: 'LightSalmon', colors: '#FFA07A'},
  {paletteName: 'LightSeaGreen', colors: '#20B2AA'},
  {paletteName: 'LightSkyBlue', colors: '#87CEFA'},
  {paletteName: 'LightSlateGray', colors: '#778899'},
  {paletteName: 'LightSlateGrey', colors: '#778899'},
  {paletteName: 'LightSteelBlue', colors: '#B0C4DE'},
  {paletteName: 'LightYellow', colors: '#FFFFE0'},
  {paletteName: 'Lime', colors: '#00FF00'},
  {paletteName: 'LimeGreen', colors: '#32CD32'},
  {paletteName: 'Linen', colors: '#FAF0E6'},
  {paletteName: 'Magenta', colors: '#FF00FF'},
  {paletteName: 'Maroon', colors: '#800000'},
  {paletteName: 'MediumAquaMarine', colors: '#66CDAA'},
  {paletteName: 'MediumBlue', colors: '#0000CD'},
  {paletteName: 'MediumOrchid', colors: '#BA55D3'},
  {paletteName: 'MediumPurple', colors: '#9370D8'},
  {paletteName: 'MediumSeaGreen', colors: '#3CB371'},
  {paletteName: 'MediumSlateBlue', colors: '#7B68EE'},
  {paletteName: 'MediumSpringGreen', colors: '#00FA9A'},
  {paletteName: 'MediumTurquoise', colors: '#48D1CC'},
  {paletteName: 'MediumVioletRed', colors: '#C71585'},
  {paletteName: 'MidnightBlue', colors: '#191970'},
  {paletteName: 'MintCream', colors: '#F5FFFA'},
  {paletteName: 'MistyRose', colors: '#FFE4E1'},
  {paletteName: 'Moccasin', colors: '#FFE4B5'},
  {paletteName: 'NavajoWhite', colors: '#FFDEAD'},
  {paletteName: 'Navy', colors: '#000080'},
  {paletteName: 'OldLace', colors: '#FDF5E6'},
  {paletteName: 'Olive', colors: '#808000'},
  {paletteName: 'OliveDrab', colors: '#6B8E23'},
  {paletteName: 'Orange', colors: '#FFA500'},
  {paletteName: 'OrangeRed', colors: '#FF4500'},
  {paletteName: 'Orchid', colors: '#DA70D6'},
  {paletteName: 'PaleGoldenRod', colors: '#EEE8AA'},
  {paletteName: 'PaleGreen', colors: '#98FB98'},
  {paletteName: 'PaleTurquoise', colors: '#AFEEEE'},
  {paletteName: 'PaleVioletRed', colors: '#D87093'},
  {paletteName: 'PapayaWhip', colors: '#FFEFD5'},
  {paletteName: 'PeachPuff', colors: '#FFDAB9'},
  {paletteName: 'Peru', colors: '#CD853F'},
  {paletteName: 'Pink', colors: '#FFC0CB'},
  {paletteName: 'Plum', colors: '#DDA0DD'},
  {paletteName: 'PowderBlue', colors: '#B0E0E6'},
  {paletteName: 'Purple', colors: '#800080'},
  {paletteName: 'Red', colors: '#FF0000'},
  {paletteName: 'RosyBrown', colors: '#BC8F8F'},
  {paletteName: 'RoyalBlue', colors: '#4169E1'},
  {paletteName: 'SaddleBrown', colors: '#8B4513'},
  {paletteName: 'Salmon', colors: '#FA8072'},
  {paletteName: 'SandyBrown', colors: '#F4A460'},
  {paletteName: 'SeaGreen', colors: '#2E8B57'},
  {paletteName: 'SeaShell', colors: '#FFF5EE'},
  {paletteName: 'Sienna', colors: '#A0522D'},
  {paletteName: 'Silver', colors: '#C0C0C0'},
  {paletteName: 'SkyBlue', colors: '#87CEEB'},
  {paletteName: 'SlateBlue', colors: '#6A5ACD'},
  {paletteName: 'SlateGray', colors: '#708090'},
  {paletteName: 'SlateGrey', colors: '#708090'},
  {paletteName: 'Snow', colors: '#FFFAFA'},
  {paletteName: 'SpringGreen', colors: '#00FF7F'},
  {paletteName: 'SteelBlue', colors: '#4682B4'},
  {paletteName: 'Tan', colors: '#D2B48C'},
  {paletteName: 'Teal', colors: '#008080'},
  {paletteName: 'Thistle', colors: '#D8BFD8'},
  {paletteName: 'Tomato', colors: '#FF6347'},
  {paletteName: 'Turquoise', colors: '#40E0D0'},
  {paletteName: 'Violet', colors: '#EE82EE'},
  {paletteName: 'Wheat', colors: '#F5DEB3'},
  {paletteName: 'White', colors: '#FFFFFF'},
  {paletteName: 'WhiteSmoke', colors: '#F5F5F5'},
  {paletteName: 'Yellow', colors: '#FFFF00'},
  {paletteName: 'YellowGreen', colors: '#9ACD'},
]

export {COLOR_PALETTES, COLORS}
